### ISSUE TITLE
DURNZISOSMSOXISDURRRRRJCIDSHS

### ISSUE THREAD

**Issue by crackcocacola** [rac1sm/phobos-1.7.2-built-jar#1]
https://user-images.githubusercontent.com/71105845/108445438-430f0380-7211-11eb-9f3a-85d2ab81e0f7.mp4

**Comment by rac1sm** [comment]
u should really use medal.tv

**Comment by crackcocacola** [comment]
> u should really use medal.tv

idk

**Comment by rac1sm** [comment]
it is big fps no watermark

**Comment by crackcocacola** [comment]
> it is big fps no watermark

xbox game bar also cool
